language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

matrix:
    include:
        - name: 'Lowest dependencies'
          php: 7.2
          env: DEPENDENCIES="--prefer-lowest --prefer-stable"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction $DEPENDENCIES

script:
  - composer all-ci

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
