name: Tests and linting

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3']
        dependencies: ['']
        include:
          - { php-version: '8.0', dependencies: '--prefer-lowest --prefer-stable' }

    name: PHP ${{ matrix.php-version }} ${{ matrix.dependencies }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, zip
          coverage: xdebug
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-progress ${{ matrix.dependencies }}

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover coverage-clover.xml

      - name: Submit coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
            flag-name: ${{ github.job }}-PHP-${{ matrix.php-version }} ${{ matrix.dependencies }}
            file: coverage-clover.xml
            parallel: true

  tests-finished:
      needs: tests
      if: ${{ always() }}
      runs-on: ubuntu-latest
      steps:
        - name: Notify Coveralls of finished builds
          uses: coverallsapp/github-action@v2
          with:
            parallel-finished: true

  codestyle:
      name: "Code style and static analysis"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
            extensions: mbstring, intl
            tools: composer:v2

        - name: Install dependencies
          run: composer update --no-progress

        - name: Lint
          run: composer lint

        - name: Run checks
          run: composer analyze

  markdown-link-check:
    name: "Markdown link check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
